### ISSUE TITLE
Transaction ID is returned as string, not int

### ISSUE THREAD

**Issue by MarcinOrlowski** [bgaluszka/mbank#11]
Transaction ID is returned as string, not int. The line I refer to is here:

https://github.com/bgaluszka/mbank/blob/master/lib/bgaluszka/Mbank/Mbank.php#L274

Is there any reason it is not

    'id' => (int)$this->xpath->evaluate('string(@data-id)', $node),

Have you experienced non numeric IDs in mbank?

**Comment by MarcinOrlowski** [comment]
Can we have this int then?

**Comment by bgaluszka** [comment]
I wouldn't assume int since it's kind of "3rd party undocumented API", so that casting would have to go with some check I think.

**Comment by MarcinOrlowski** [comment]
Makes sense. Will change my end to expect strings as ids
