### ISSUE TITLE
Realizowanie przelewu do niezdefiniowanego odbiorcy

### ISSUE THREAD

**Issue by michuCodeStore** [bgaluszka/mbank#12]
Czy jest możliwe zrobienie przelewu do dowolnego odbiorcy (niezdefiniowanego w książce)? Wiem, że trzeba będzie to zweryfikować kodem ale to nie problem gdy używasz aplikacji mobilnej.
W requestach widzę, że jest coś takiego jak 

> "/pl/MyTransfer/TransferCommon/PrepareTransferBase"

 i tutaj pojawia się pole "recipientId" tylko w żadnym requescie nie widzę gdzie to jest zwracane. A wykonanie przelewu 

> "/pl/MyTransfer/TransferDomestic/IntermediateSubmitTransferDomestic" 

wymaga tego parametru (recipientId).

**Comment by bgaluszka** [comment]
W tej chwili nie ma takiej możliwości.
