### ISSUE TITLE
dyrektywa PSD2

### ISSUE THREAD

**Issue by michuCodeStore** [bgaluszka/mbank#18]
od 14.09.2019 wchodzi zmiana procesu logowania:
> inaczej będziesz logować się na swoje konto w internecie. Poza identyfikatorem i hasłem poprosimy Cię, abyś dodatkowo potwierdził logowanie hasłem SMS lub mobilną autoryzacją (logowanie do aplikacji mobilnej się nie zmieni).

czy myślicie, że jest jakaś droga obejścia tego i korzystania dalej z kodu?

**Comment by bgaluszka** [comment]
Jak dodadzą to raczej będzie cieżko. Mam natomiast lokalnie w miarę (w podobnym zakresie co ta biblioteka) zrobioną komunikację z ich API SOAP z którego korzysta ich aplikacja mobilna i tam nie ma i nie będzie tej autoryzacji SMS (dodatkowo tam jest token zamiast loginu i hasła, co jest dodatkowym plusem). Nie wiem natomiast kiedy mi się to uda opublikować bo to mam go w takiej wersji mocno deweloperskiej i nie korzystam z tego na codzień, tylko z ciekawości to zrobiłem :/

**Comment by michuCodeStore** [comment]
rozumiem, jakieś wskazówki odnośnie tego rozwiązania API SOAP? Ewentualnie opcja współdzielenia, muszę coś wprowadzić jako alternatywę, zastanawiam się jeszcze nad oficjalną drogą: https://developer.api.mbank.pl/ ale tu raczej będzie to płatne rozwiązanie i bez większych opcji rozwoju :)

**Comment by bgaluszka** [comment]
O to nawet tego nie znałem, ten SOAP robiłem spory czas temu i raczej tego API wtedy jeszcze nie było, a wygląda dobrze :) Dzięki!

**Comment by pfurmaniak** [comment]
Niestety w Zasadach korzystania z API (https://developer.api.mbank.pl/pages/service-policy) możemy wyczytać (§3 ust. 1), że:

> Uczestnikiem może być wyłącznie:
> 1. posiadający zezwolenie na świadczenie usług płatniczych AISP, PISP lub CBPII,
> 2. dostawca usług płatniczych, który złożył do właściwego organu nadzoru wniosek o stosowne zezwolenie na prowadzenie działalności jako AISP, PISP lub CBPII.

Więc obawiam się, że nie będzie ono dostępne dla wszystkich.

@bgaluszka jakaś szansa na podzielenie się w najbliższym czasie tym kodem rozmawiającym z serwisem SOAP?

**Comment by bgaluszka** [comment]
Odkurzyłem ten kod SOAP ale niestety nie wykonuje się nawet poprawnie proces logowania (a nie wiem jak dalej). Dodatkowo od tamtego czasu mBank/Android się zmieniły i nie mogę wgrać sobie na telefon certyfikatów do MITM/proxy, żeby zerknąć co jest nie tak. Więc potrzbuję chwilę czasu, żeby to ogarnąć lepiej :/

**Comment by b44x** [comment]
@bgaluszka - możesz się podzielić tym co masz, bo też brałem się za appkę - a zawsze będzie szybciej.

**Comment by MrDefacto** [comment]
Za autoryzację urządzenia odpowiada wartość cookie o nazwie mBank8. Tymczasowym rozwiązaniem jest wydłubanie tej wartości z autoryzowanej przeglądarki - no i oczywiście ustawianie jej w przesyłanych przez skrypt nagłówkach. U mnie działa z tym, że na modyfikowanym przeze mnie APIv2 z Studio85. Taki quickfix dla wszystkich którzy zostali odcięci od pobierania operacji z mBank.

**Comment by michuCodeStore** [comment]
ustawienie tego cookie mbank8 na pewno pomaga? Mi po zalogowaniu i próbie przejścia na inną stronę wyrzuca błąd HTTP Status Code 520

**Comment by jwilk** [comment]
Pomaga, ale nie wystarcza: https://github.com/jwilk/mbank-cli/issues/74#issuecomment-531966373

Z tego co widzę, w mBanku HTTP 520 oznacza, że się zalogowałeś hasłem, ale nie przeszedłeś 2FA.

**Comment by m-per** [comment]
Jakby ktoś się nie zorientował to zostało to już rozwiązane tutaj:
https://github.com/bgaluszka/mbank/issues/21
