### ISSUE TITLE
Can not connect to mBank

### ISSUE THREAD

**Issue by m-per** [bgaluszka/mbank#19]
mBank has made some changes to the website and you can't log in now:

Fatal error: Uncaught exception 'RuntimeException' with message 'login() failed' in /PATHHERE/Mbank.php:124 Stack trace: #0 /PATHHERE/SCRIPTHERE.php(21): Mbank->login('LOGINHERE', 'PASSWORDHERE') #1 {main} thrown in /PATHHERE/Mbank.php on line 124

The problem was already solved in mbank-cli project, so it may be good idea to look there for solution:
https://github.com/jwilk/mbank-cli/issues/71

**Comment by michuCodeStore** [comment]
po dodaniu headera oraz przesłaniu danych do logowania jako JSON - działa

`$fields = array(
            'DfpData' => [
                'dfp' => '',
                'errorMessage' => null,
                'scaOperationId' => ''
            ],
            'HrefHasHash' => false,
            'Lang' => '',
            'Password' => $loginData['password'],
            'Scenario' => 'Default',
            'Seed' => '',
            'UWAdditionalParams' => [
                'InOut' => null,
                'ReturnAddress' => null,
                'Source' => null,
            ],
            'UserName' => $loginData['username'],
        );
        $response = $this->curl(array(
            CURLOPT_URL => $this->url . '/Account/JsonLogin',
            CURLOPT_POST => true,
            CURLOPT_POSTFIELDS => json_encode($fields),
            CURLOPT_HTTPHEADER => array('Content-Type: application/json;charset=UTF-8', 'X-Requested-With: XMLHttpRequest')
        ));`

**Comment by b44x** [comment]
https://github.com/bgaluszka/mbank/pull/20/commits/e00f7ea2e4342468212a7aaa2be45bab5f927e25
