### ISSUE TITLE
Nie działa pobieranie danych z banku

### ISSUE THREAD

**Issue by m-per** [bgaluszka/mbank#21]
Zgodnie z przewidywaniami pobieranie danych o przelewach przestało działać. 

Aplikacja WWW mBanku po zalogowaniu proponuje dodanie komputera do zaufanych, co trzeba potwierdzić aplikacją mobilną (być może również innymi sposobami można). Wówczas można się logować bez problemu jak dawniej.

Myślę że można pominąć konieczność sprawdzania SMS jak ktoś wcześniej sugerował, i zrobić tak, aby skrypt przy pierwszym połączeniu dodał się jako "zaufany komputer", jednorazowo potwierdzając tą operację aplikacją mobilną.

**Comment by m-per** [comment]
Wygląda na to, że po dodaniu przeglądarki do "urządzeń zaufanych" można ustawić w kodzie cookie mBank8 na taką samą wartość, jak ten cookie w przeglądarce.
Następnie ustawić DFP w kodzie na taką samą wartość jak DFP pobrany z przeglądarki komendą (w konsoli): Ebre.Behaviour.GetCurrentDfp()._rejectionHandler0
W ten sposób przechodzimy logowanie, ale utknąłem na pobraniu danych, dalej nie działa.

**Comment by m-per** [comment]
Musiałem sobie trochę przypomnieć PHP i popróbować, ale wygląda na to, że jednak działa...:

Sposób nie jest skomplikowany:
Do __construct() do opcji CURL dodajemy:
CURLOPT_COOKIE		=> "mBank8=tutaj nasz cookie mBank8 z przeglądarki",
CURLOPT_COOKIEFILE	=> 'ciacha',
CURLOPT_COOKIEJAR       => 'ciacha'

Przy logowaniu zmieniamy kod sekcji DfpData na:
'DfpData' => [
	'dfp' => $dfp,
	'errorMessage' => null,
	'scaOperationId' => uniqid()

],

jak uzyskać $dfp pisałem powyżej. I tyle, pobiera poprawnie.

**Comment by dequire** [comment]
@m-per, zrobiłem jak opisałeś i wszystko znowu działa. Dzięki!

Mała korekta - musiałem dodać http_build_query przy konstrukcji postfieldów, żeby ominąć array to string conversion error.

```
$dfp = <wyciągnięty z przeglądarki>;
$response = $this->curl(array(
  CURLOPT_URL        => $this->url . '/'.$this->countryCode.'/Account/JsonLogin',
  CURLOPT_POST       => true,
  CURLOPT_POSTFIELDS => **http_build_query**(array(
    'UserName' => $username,
    'Password' => $password,
    'Seed'     => '',
    'Lang'     => '',
    'DfpData'  => array (
      'dfp' => $dfp,
      'errorMessage' => null,
      'scaOperationId' => uniqid()	
    )
  )),
));
```

Warto zrobić z tego PRa :-)

**Comment by m-per** [comment]
Ja zamiast http_build_query() mam tam json_encode(), ale już nie pamiętam czy to dodawałem teraz czy wcześniej było.

**Comment by telemetrik** [comment]
@m-per Dołączam się do prośby o PR. :)

**Comment by michuCodeStore** [comment]
zauważyłem, że wywołanie "/pl" po logowaniu nie zwraca poprawnej wartości dla: token. 
poniższy endpoint zwraca odpowiednie dane:
`$opts = array(CURLOPT_URL => 'https://online.mbank.pl/pl/setup/data');`
`$response = $this->curl($opts);`
`$this->token = $response['antiForgeryToken'];`

**Comment by michuCodeStore** [comment]
prawdopodobnie przy okazji zmian z "nowym pulpitem" część adresów przestała działać jak wcześniej. Np:
`/MyDesktop/Desktop/SetNavigationToAccountHistory`
w metodzie:
`operations`

i samo zwracanie danych o przelewach przestało działać

**Comment by perskinet** [comment]
Hmm czy pobieranie tego dfp nadal działa?:

Ebre.Behaviour.GetCurrentDfp()._rejectionHandler0
VM960:1 Uncaught ReferenceError: Ebre is not defined
    at <anonymous>:1:1

Jest też kilka cookie w mbanku CSSID, DFID, który dokładnie cookie podać do logowania?

**Comment by mRozynski** [comment]
pobieranie działa ale na stronie logowania (https://online.mbank.pl/pl/Login), potem już pokazuje error

**Comment by perskinet** [comment]
Wyciągnąłem sobie z headera, fajnie byłoby skrobnąć jakiegoś docsa co i jak po kolei zrobić :) A mbank8 nie znalazłem, bo nie zauważyłem scrolla :D Sorki za zawracanie gitary, właśnie się zalogowałem i mam historię, dzięki!

**Comment by tryllu** [comment]
Możecie wskazać jak obecnie wyciągnąć DFP? Albo jestem głupi albo coś się zmieniło :)
Widze, że za to odpowiedzialny jest fingerprint.js.
