### ISSUE TITLE
Kompatybilność po wymaganiu dodaniu urządzenia do zaufanych

### ISSUE THREAD

**Issue by perskinet** [bgaluszka/mbank#23]
Witam,

Czy Wasza biblioteka działa po zmianie z koniecznością dodawania urządzeń do zaufanych? :)

Pozdrawiam,
Szymon Perski

**Comment by michuCodeStore** [comment]
Witam,

tak działa - większość opisana tutaj:
https://github.com/bgaluszka/mbank/issues/18
