### ISSUE TITLE
Consider contributing the code to Woob

### ISSUE THREAD

**Issue by wrobelda** [bgaluszka/mbank#27]
Hi,

There is a generic platform that supports scraping data from financial institutions: https://woob.tech (formerly known as Weboob). The platform itself is in turn supported by an array of open source personal finance applications, including Skrooge and KMyMoney – the latter of which I am one of the maintainers. 

It would be beneficial to mBank users in CEE if KMyMoney and Skrooge gained support for it via Woob, so please consider contributing the code there.

I do understand that Woob is Python, while your lib is PHP, but at the end of the day the core problem is the know-how on how to scrape the bank data, and Woob has some otherwise pretty good docs, examples and Dev community, so hopefully you can find time and energy to commit to it. 

In any case, please feel free to reach out for any help.

PS. FYI, I will be submitting a similar request to https://github.com/jwilk/mbank-cli/issues/94

**Comment by bgaluszka** [comment]
Thank you FYI, I'll look into it :)

**Comment by wrobelda** [comment]
FYI, I found some time and came up with a MVP here: https://gitlab.com/woob/woob/-/merge_requests/685

Feel free to test, and, if interested, I'm happy to grant a write permission to the branch behind the PR.
