### ISSUE TITLE
Wyszukiwanie

### ISSUE THREAD

**Issue by dusta** [bgaluszka/mbank#4]
Czy da się zrobić bardziej rozbudowane wyszukiwanie Tytuł Przelewu ?

**Comment by bgaluszka** [comment]
Raczej tak :) Przyjżę się temu przez weekend.

**Comment by bgaluszka** [comment]
W zasadzie to możesz to robić już w tej chwili. Dodałem do przykładu https://github.com/bgaluszka/mbank#search-account zastosowanie, pole "SearchText".
