### ISSUE TITLE
CSV export from other IBAN

### ISSUE THREAD

**Issue by SystemZ** [bgaluszka/mbank#5]
Hi, thanks for this great lib! It's saving me a lot of time every day :)

I noticed that CSV export is from default (main) bank account only.
Is there a way to export from other account providing IBAN number? Maybe I'm missing something?

**Comment by bgaluszka** [comment]
Export is sort of unfinished hence undocumented :) Give me couple of days and I'll update code and documentation on how to use it.

**Comment by SystemZ** [comment]
Ok, no problem :)

**Comment by bgaluszka** [comment]
I've updated export method. It'll stay undocumented for now, but here is how you can use it:

```php
<?php
require_once 'vendor/autoload.php';

$mbank = new \bgaluszka\Mbank\Mbank();
$mbank->login('id', 'password');

// all transaction from begining of given month
$csv = $mbank->export('iban', array(
    'daterange_from_day' => '1',
    'daterange_from_month' => date('m'),
    'daterange_from_year' => date('Y'),
    'daterange_to_day' => date('d'),
    'daterange_to_month' => date('m'),
    'daterange_to_year' => date('Y'),
));
// you probably want to convert that to UTF-8
$csv = iconv('WINDOWS-1250', 'UTF-8', $csv);

file_put_contents('mbank.csv', $csv);

$mbank->logout();
```

Basically it now requires you to provide IBAN. You can always look at source https://github.com/bgaluszka/mbank/blob/master/lib/bgaluszka/Mbank/Mbank.php#L207 for additional parameters. Please let me know if it works for you.

**Comment by SystemZ** [comment]
Awesome! It's working now :)
