### ISSUE TITLE
Problem z rachunkiem na którym jestem 

### ISSUE THREAD

**Issue by gavron7** [bgaluszka/mbank#6]
Logowanie do rachunku ktory posiada przypisany rachunek indywidualy i biznesowy jest ok, ale problem sie pojawia jesli mam przypisane pelnomocnitwo do innego rachunku (ja mam pelnomocnictwo do rachunku dziecka), i jak loguje sie do siebie to otrzymuje taki komunikat o bledzie:

izzyKONTO 0 PLN

Fatal error: Uncaught exception 'Exception' with message 'curl() failed - HTTP Status Code 500' in /var/www/html/mbank/mbank/lib/bgaluszka/Mbank/Mbank.php:352 Stack trace: #0 /var/www/html/mbank/mbank/lib/bgaluszka/Mbank/Mbank.php(103): bgaluszka\Mbank\Mbank->curl(Array) #1 /var/www/html/mbank/mbank/index.php(11): bgaluszka\Mbank\Mbank->profile('business') #2 {main} thrown in /var/www/html/mbank/mbank/lib/bgaluszka/Mbank/Mbank.php on line 352

bo u mnie nie ma biznesowego konta, ale blednie pokazuje bo pokazuje tylko rachunek pelnomocnika a nie moj :(

**Comment by bgaluszka** [comment]
Niestety nie mam dostępu do takiego rachunku z pełnomocnictwem, ale może jakoś się uda :) Czy ten błąd pojawia się jeżeli wybierzesz profil indywidualny? Czy on pojawia się w momencie jak wybierzesz biznesowy?

**Comment by gavron7** [comment]
Jest tak:
konto prywatne + biznesowe = działa ok
konto prywatne + pełnomocnictwo = wywala błąd na koncie biznesowym, nie wiem jak nazywa się konto "z pełnomocnictwem" . Wywaliłem "busines" ze skryptu i śmiga :> 

Kawał dobrej roboty. Wrzuciłem go z moimi dodatkami do iNETLMS na githubie :>

**Comment by bgaluszka** [comment]
Jak w mbanku zalogujesz się i przełączasz profile to idzie zapytanie do `/pl/LoginMain/Account/JsonActivateProfile` (wywoływane podobnie jak tutaj https://github.com/bgaluszka/mbank/blob/master/lib/bgaluszka/Mbank/Mbank.php#L96). Możesz mi podesłać `profileCode` przy przełączeniu na pełnomocnictwo? W konsoli będzie je widać (F12).

**Comment by gavron7** [comment]
pokierujesz mnie łopatologicznie? bo na consoli żadnych w sumie sensownych danych nie ma z tych co piszesz :(

**Comment by bgaluszka** [comment]
Może zanim to zrobimy powiedz mi czy po zalogowaniu się do mbanku masz do wyboru profil inny niż indywidualny i firmowy, że dostać się do konta którego jesteś pełnomocnikiem?

**Comment by gavron7** [comment]
Tak. Mam indywidualne, pełnomocnictwo, wszystkie i firmowe mogę założyć. :)
bo na innym koncie mam indywidualne i firmowe i smigaja oba ok
15-03-2016 22:44, "Bartosz Gałuszka" <notifications@github.com> napisał(a):

**Comment by bgaluszka** [comment]
Będę opisywał Firefox, jak korzystasz z Chrome to proces wygląda podobnie. Po zalogowaniu się otwórz konsole F12 i zaznacz "persistent", a potem zmień profil na pełnomocnictwo. Powinno to wygenerować zapytanie do https://online.mbank.pl/pl/LoginMain/Account/JsonActivateProfile. Interesuje mnie co jest wtedy wysyłane. Jak klikniesz prawym na takie zapytanie to powinieneś móc skopiować lub podejrzeć wartość POSTjaka jest wysyłana. To jest jest w przypadku przełączenia na profil indywidualny wartość `profileCode=I` :)

![persistent](https://cloud.githubusercontent.com/assets/176279/13795824/61a27eca-eb03-11e5-972c-a8c7f8fa23f0.png)
![profile](https://cloud.githubusercontent.com/assets/176279/13795823/61a24c84-eb03-11e5-8918-fc54adff0426.png)

**Comment by gavron7** [comment]
ja mam chyba ruski internet czy coś takiego bo u mnie takich rzeczy nie ma :> kurcze spróbuję porobić Ci fotki co i jak robię ale nie mam tego w konsoli (Chrome)
