### ISSUE TITLE
Realizowanie transakcji zdefiniowanych

### ISSUE THREAD

**Issue by grekpg** [bgaluszka/mbank#7]
Czy była by możliwość realizacji przelewów zdefiniowanych ? One nie wymagają potwierdzenia więc chyba dało by się to zrobić ?

**Comment by bgaluszka** [comment]
Postaram się dodać w najbliższym czasie :)

**Comment by gavron7** [comment]
a jaki jest sens takiego rozwiązania? tzn jaki sens zdalnie obsługiwać przelewy zdefiniowane?

**Comment by bgaluszka** [comment]
Mogę sobie wyobrazić jakiś system "CRM", w którym ty/ktoś/automat wykonuje przelewy zdefiniowane do kontrachentów. Takie przelewy mogą mieć różne kwoty zależne od wybranych czynników.

**Comment by grekpg** [comment]
Sens jest duży - jedno mając pod konta - można sobie dowolnie rozdzielać pieniądze - na podstawie wyższej logiki a nie tego co bank oferuje. (np konto bieżące, oszczędnościowe i konta celowe np na podatki itd  -z automatu można sobie rozdzielać środki.
Drugie-  jak napisane - realizować płatności do dowolnej ilości odbiorców zdefionowanych na podstawie zakięgowanych faktur. 
Można też dodać stałych odbiorców nawet dla osoby prywatnej i realizować przelewy z programu swojego a nie wyklikując z banku.
Kolejne - można sobie zrobić programy oszczędnościowe - mbank ma max 5 zł z operacji na oszczędności do tego można mieć jedna skarbonke tak można sobie zrobić dowolną ilość i logikę.

**Comment by gavron7** [comment]
no ok. :>

**Comment by bgaluszka** [comment]
Dodałem możliwość wykonywania operacji zdefiniowanych. Całość komplikuje trochę to, że książka adresowa może zawierać duplikaty (nazwy kontaktów i zdefiniowanych przy nich operacji nie są unikalne), więc obsługa zdefiniowanych operacji zależeć będzie pewnie od zawartości książki adresowej. Nowe funkcje oznaczyłem jako eksperymentalne, więc proszę programować uważnie :) Kod do tego mógłby wyglądać mniej więcej tak:

```php
require_once 'vendor/autoload.php';

$mbank = new \bgaluszka\Mbank\Mbank();
$mbank->login('login', 'password');

// definiuje z jakiego profilu/konta pójdzie przelew
$mbank->profile('individual');

foreach ($mbank->contacts() as $key => $contact) {
    if ($contact['name'] === 'CONTACT NAME') {
        if ($contact = $mbank->contact_details($contact['id'])) {
            foreach ($contact['transfers'] as $transfer) {
                if ($transfer['name'] === 'TRANSFER NAME') {
                    $amount = 1.01;
                    $title = 'Przelew środków';

                    // $amount i $title można pominąć jeżeli są zdefiniowane i nie muszą się zmienić
                    $data = $mbank->transfer_prepare($contact['contactId'], $transfer['id'], $amount, $title);

                    if ($mbank->transfer_submit($contact['contactId'], $transfer['id'], $data)) {
                        echo "Przelew wykonany\n";
                    } else {
                        echo "Nie udało się wykonać przelewu\n";
                    }

                    break 2;
                }
            }
        }
    }
}

$mbank->logout();
```

**Comment by michuCodeStore** [comment]
Czy jest możliwe zrobienie przelewu do dowolnego odbiorcy (niezdefiniowanego w książce)? Wiem, że trzeba będzie to zweryfikować kodem ale to nie problem gdy używasz aplikacji mobilnej.
W requestach widzę, że jest coś takiego jak 

> "/pl/MyTransfer/TransferCommon/PrepareTransferBase"

 i tutaj pojawia się pole "recipientId" tylko w żadnym requescie nie widzę gdzie to jest zwracane. A wykonanie przelewu 

> "/MyTransfer/TransferDomestic/IntermediateSubmitTransferDomestic" 

wymaga tego parametru (recipientId).
