### ISSUE TITLE
pobieranie przelewów

### ISSUE THREAD

**Issue by michuCodeStore** [bgaluszka/mbank#8]
Pobierając listę przelewów nie otrzymujemy pełnej listy, dopiero po przejściu do 'starej' listy otrzymujemy przelewy typu "PRZELEW EE-PRZYCHODZĄCY".

**Comment by bgaluszka** [comment]
Czy chodzi o to (tak upraszczając), że wynik `$mbank->operations()` jest inny od `$mbank->export()`?

**Comment by michuCodeStore** [comment]
Tak.
Wcześniej nie było tego typu, być może ktoś nie podpiął pod nowy widok tego rodzaju przelewów.
Po zalogowaniu się na stronę i przejściu na zmianę widoku historii można znaleźć przelewy tego typu.

**Comment by bgaluszka** [comment]
A co to za rodzaj operacji/przelewu?

**Comment by michuCodeStore** [comment]
PRZELEW EE-PRZYCHODZĄCY

**Comment by bgaluszka** [comment]
A czy mogę coś zrobić, żeby mieć taki przelew u siebie? :)

**Comment by michuCodeStore** [comment]
już nieaktualne, dla tego typu przelewów nie można wyszukiwać po tytule przelewu, ale sam przelew pokazuje się dla metody `$mbank->operations()` bez parametrów.
Dziękuję
