### ISSUE TITLE
Nazwa odbiorcy w operacjach

### ISSUE THREAD

**Issue by grekpg** [bgaluszka/mbank#9]
Hm w liście operacji nie ma Nazwa odbiorcy ? w historii mbanku są te dane ale nie są odczytywane ? Baardzo by się to przydało - ułatwiło by to księgowanie.

Chodzi o pola z histori: 

Nazwa odbiorcy
DIALCOM24 SP. Z O.O.
Rachunek odbiorcy
46 1140 2004 0000 3502 7203 2007
Bank odbiorcy
MBANK S.A.
Adres odbiorcy
UL.KANCLERSKA 15
Miejscowość odbiorcy
60-327 POZNAŃ POLSKA

**Comment by bgaluszka** [comment]
Lista operacji zawiera te same dane co "Historia" w serwisie transakcyjnym i to jest coś mało szczegółowego. Z tego co widzę mógłbym dorobić możliwość pobrania szczegółów danej transakcji (analogicznie jak to jest w "Historii"). Inna możliwość to pobranie historii w postaci pliku CSV. Tutaj jest przykład https://github.com/bgaluszka/mbank/issues/5#issuecomment-77033941 jak to zrobić.

**Comment by grekpg** [comment]
Jeżeli podstawową operacją jest lista transakcji to myślę że bardzo by się przydały te dane - bez tego mam x takich samych operacji.

**Comment by bgaluszka** [comment]
Przyjżałem się temu trochę, ale pobranie szczegółów transakcji z serwisu jest trochę skomplikowane bo zwracany jest html, który zależy od rodzaju operacji. Na moim koncie indywidualnym doliczyłem się 16 rodzajów transakcji (a pewnie jest więcej) i każda ma innych html. Na razie proponuje Ci korzystanie z CSV, jeżeli potrzebujesz czegoś bardziej szczegółowego niż to co zwraca metoda `operations()`.
